server:
  port: 8101

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 81.69.4.237:8848
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'